### ISSUE TITLE
关于苹果间视频通话的问题

### ISSUE THREAD

**Issue by FireOra** [TangSengDaoDao/TangSengDaoDaoiOS#4]
发现苹果间加了好友，如果双方未发过一条信息的情况下进行语音视频就没有办法接通。测试机型iphone X与iphone 12，是在购买的语音视频模块且接通后进行的测试，唐僧叨叨官方demo没法注册就没有进行测试，能不能麻烦作者看看有没有这个问题

**Comment by tangtaoit** [comment]
收到，我们验证下。

**Comment by FireOra** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by tangtaoit** [comment]
已修复
