### ISSUE TITLE
关于苹果机与安卓机语音视频通话的问题

### ISSUE THREAD

**Issue by FireOra** [TangSengDaoDao/TangSengDaoDaoiOS#5]
我安卓（oppo findx3）使用贵公司的demo向IOS用户（iphone 11 pro）进行通话测试时，当对方把APP从后台清理掉后，我向对方发起通话请求时，对方有通话信息推送通知，对方点击通知后跳转到接通界面，点击“接听”后一直显示连接中，无法正常通话。如果可以的话麻烦贵公司排查下问题所在，谢谢
![微信图片_20240703105143](https://github.com/TangSengDaoDao/TangSengDaoDaoiOS/assets/137872433/19761a96-fb70-4660-8816-8cf49d0f1c00)

**Comment by FireOra** [comment]
如果APP仅仅挂在后台则能正常收到推送也能正常接通。我们在开启了语音模块后情况却刚好相反：APP挂后台无法接通，APP杀掉却很正常

**Comment by tangtaoit** [comment]
> 我安卓（oppo findx3）使用贵公司的demo向IOS用户（iphone 11 pro）进行通话测试时，当对方把APP从后台清理掉后，我向对方发起通话请求时，对方有通话信息推送通知，对方点击通知后跳转到接通界面，点击“接听”后一直显示连接中，无法正常通话。如果可以的话麻烦贵公司排查下问题所在，谢谢 ![微信图片_20240703105143](https://private-user-images.githubusercontent.com/137872433/345265253-19761a96-fb70-4660-8816-8cf49d0f1c00.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTgzNzYsIm5iZiI6MTcxOTk5ODA3NiwicGF0aCI6Ii8xMzc4NzI0MzMvMzQ1MjY1MjUzLTE5NzYxYTk2LWZiNzAtNDY2MC04ODE2LThjZjQ5ZDBmMWMwMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwOTE0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDFhYTZhMWI2ODFlNWVlYzRmZjI4ZmVmZTU0NGI4YWJlNmM1NjllMTk5MDI0ZTU4NTdhZThiMWEyMjBiNWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kXv6xNk6vcojEbwXNryV2GWPok4a5P5-y76p-hz4XXI)

Android之间不存在这个问题吧？是否只存在Android与iOS或iOS与iOS之间？

**Comment by FireOra** [comment]
Android与Android，iOS与iOS暂时没问题，但为以防万一，正在组织更多人手进行测试与记录，后续我会将测试结果整理再发上来，麻烦贵公司到时候抽空看看

**Comment by tangtaoit** [comment]
> Android与Android，iOS与iOS暂时没问题，但为以防万一，正在组织更多人手进行测试与记录，后续我会将测试结果整理再发上来，麻烦贵公司到时候抽空看看

我们在测试这个问题，Android与Android之间暂时没发现问题，iOS与iOS之间有复现，目前我们测试下来看来像iOS的问题。

**Comment by FireOra** [comment]
> > Android与Android，iOS与iOS暂时没问题，但为以防万一，正在组织更多人手进行测试与记录，后续我会将测试结果整理再发上来，麻烦贵公司到时候抽空看看
> 
> 我们在测试这个问题，Android与Android之间暂时没发现问题，iOS与iOS之间有复现，目前我们测试下来看来像iOS的问题。

我们这边也这样猜测，甚至在iOS无法正常接通的情况下，双方互发消息后，又能正常通话。我们猜测是“某些地方安卓和iOS默认不打通”，但具体还无法验证

**Comment by tangtaoit** [comment]
1. 更新下最新WuKongIMiOS SDK （版本：1.0.8）
2. coturn加上no-stun配置（表示都走服务器转发，不走打洞）
<img width="299" alt="image" src="https://github.com/TangSengDaoDao/TangSengDaoDaoiOS/assets/3895878/a8f987b0-a8c3-4d39-85bf-20b0f5a5183e">

**Comment by FireOra** [comment]
好的，我这边尝试一下

**Comment by FireOra** [comment]
更新完发现如下问题，在tsdd的demo中尝试后也存在一下问题：
1.iOS方退出app放到后台后，另一方Android/iOS会看到对方仍然处于在线状态（大概10-20秒），这时候发起语音通话，iOS接收方会有震动，但不一定有推送。在有震动时iOS方进入app有通话接受通话选项，接受后仍然接不通。
2.iOS方退出且后台清理掉app后，另一方Android/iOS发起通话，iOS接收方有推送，点击推送后一直显示“连接中”，Android/iOS发起方有显示连接成功且有各种功能，但无任何声音，听不到对方声音。
麻烦作者看看能不能复现这种情况

**Comment by tangtaoit** [comment]
我们用最新的testflight的版本测试没发现问题，你们可以扫描这个下载我们的最新版本看是否有你们说的问题

<img width="329" alt="image" src="https://github.com/user-attachments/assets/d296b1fc-c55b-476e-acb7-bb501723d600">

**Comment by FireOra** [comment]
好的，想问下安卓版的demo是不是最新版？我打算也用那个做测试

**Comment by FireOra** [comment]
好的，想问下安卓版的demo是不是最新版？我打算也用那个做测试

**Comment by tangtaoit** [comment]
> 好的，想问下安卓版的demo是不是最新版？我打算也用那个做测试

安卓版的demo是新的，你可以先iOS与iOS测试，然后Android与iOS之间测试。

**Comment by FireOra** [comment]
![iOS测试结果](https://github.com/user-attachments/assets/d0b019f8-cfa2-412a-90df-ecfb4c9a0f06)
以上为我们使用唐僧叨叨iOS 1.0.6版本和Android 1.0（更新世界2024-07-08）版本进行测试的结果，麻烦作者试试能不能复现这种情况

**Comment by tangtaoit** [comment]
<img width="1299" alt="image" src="https://github.com/user-attachments/assets/d0a680e6-f9b2-4255-afa5-fa1f62cfaac8">
只有这个有问题是吧？

<img width="1204" alt="image" src="https://github.com/user-attachments/assets/7e044ecd-06a9-4f72-9c3b-7aa98c91b6b7">
这个应该是android没对接厂商推送的原因。

第一种情况我们验证下

**Comment by FireOra** [comment]
是的，只有一个问题。
oppo收不到推送应该是tsdd app没接oppo的推送，接了应该就没问题。麻烦作者大大了
